Repository Samsung/ioter, pull requests merged in 2023-06, with the labels that each got.

#71 fix to support decimal point to setTemperatureValue()
  src/things/temperature.py
Labels: bug, comp:things

#72 Update readme for supported apple homepod
  README.md
Labels: documentation

#85 Update README.md
  README.md
Labels: bug

#82 add progessbar in auto-onboarding window
  res/view/auto_onboardingWindow.ui
  src/auto_onboarding/auto_onboardingmain.py
Labels: enhancement, comp:autoOnboarding

#97 Stop otbr-agent for occupied dongle device process
  script/run
Labels: good first issue, help wanted

#108 add silabs device picture for readme update
  res/doc/efr32-mighty-gecko-starter-kit.png
  res/doc/silabs_thunderBoardSense2.png
Labels: documentation

#109 update size of silabs device picture
  res/doc/efr32-mighty-gecko-starter-kit.png
  res/doc/silabs_thunderBoardSense2.png
Labels: documentation

#112 change picture of silabs erf32 kit
  res/doc/efr32-mighty-gecko-starter-kit.png
Labels: documentation

#113 Upgrade doc links to Silicon Labs Matter Extension v2.0.0-1.1
  README.md
Labels: documentation

#115 Changing a message when close the device window that the device will remove.
  src/common/common_window.py
Labels: comp:common

#116 change light thing name (Light bulb -> Dimmable Light)
  res/view/light.ui
  src/automation/devicelayout.py
  src/common/device_command.py
  src/common/manage_device.py
  src/things/light.py
Labels: comp:things

#132 add file picture of esp dev kit for README update
  res/doc/esp32-h2-devkitm-1.png
Labels: documentation

#136 Update README.md
  README.md
Labels: documentation
