Repository Samsung/ioter, pull requests merged in 2023-05, with the labels that each got.

#5 changed the operation method of autod
  src/auto_onboarding/auto_onboardingmain.py
  src/auto_onboarding/autod.py
  src/automation/automationmain.py
  src/common/common_window.py
  src/common/device_command.py
  src/common/ioterPipe.py
  src/common/manage_device.py
  src/common/manage_usb.py
  src/main.py
Labels: enhancement, comp:autoOnboarding

#6 Update UI (slider and etc.)
  res/view/light.ui
  res/view/light_mainwindow.ui
  src/common/device_command.py
  src/common/utils.py
  src/things/humidity.py
  src/things/light.py
  src/things/lightsensor.py
  src/things/temperature.py
  src/things/windowcovering.py
Labels: enhancement, comp:common, comp:things

#9 when ioter was operated without necessary directory, no exist dir err…
  src/main.py
Labels: bug, comp:common

#10 1. fix error that device name couldn't set
  src/auto_onboarding/auto_devicelayout.py
  src/auto_onboarding/auto_onboardingmain.py
  src/auto_onboarding/autod.py
Labels: bug, comp:autoOnboarding

#18 fix description of toggle button of device more correctly
  res/icon/doorlock_off.png
  res/icon/doorlock_on.png
  src/common/device_command.py
  src/things/contact.py
  src/things/doorlock.py
  src/things/light.py
  src/things/occupancy.py
  src/things/plugin_onoff.py
Labels: comp:things
